name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  TF_VERSION: 1.6.6
  TF_WORKING_DIR: terraform

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # ----------------------------
      # OPTIONAL: Configure AWS OIDC
      # ----------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC }}
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      # - name: Terraform Format Check
      #   working-directory: ${{ env.TF_WORKING_DIR }}
      #   run: terraform fmt -check

      # - name: Terraform Validate
      #   working-directory: ${{ env.TF_WORKING_DIR }}
      #   run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

      # ----------------------------
      # APPLY ONLY ON MAIN BRANCH
      # ----------------------------
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
