name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Terraform environment"
        required: true
        type: choice
        options:
          - dev
          - nprod
          - prod

  push:
    branches:
      - main
      - future/*

permissions:
  contents: read
  id-token: write

env:
  TF_VERSION: 1.6.6
  AWS_REGION: ap-south-1

jobs:
  plan:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    # Map input → TF_WORKING_DIR
    env:
      TF_WORKING_DIR: ./${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # ----------------------------
      # Configure AWS OIDC
      # ----------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

  apply:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    # Map input → TF_WORKING_DIR
    env:
      TF_WORKING_DIR: ./${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # ----------------------------
      # Configure AWS OIDC
      # ----------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
